# Generated by Django 4.0.3 on 2022-04-25 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=15, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=15, unique=True)),
            ],
            options={
                'ordering': ['ticker'],
            },
        ),
    ]
